### Login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "mail": "mail@example.com",
  "password": "securePassword"
}

> {% client.global.set("auth_token", response.body.token) %}


### Save a new mood-entry
POST http://localhost:8080/entry
Content-Type: application/json
Authorization: Bearer {{auth_token}}

[
  {
    "mood": "BAD",
    "journal": "I'm feeling bad today :/",
    "date": "2023-03-15",
    "color": "#FF0000"
  },
  {
    "mood": "BAD",
    "journal": "I'm feeling bad today :/",
    "date": "2023-03-15",
    "color": "#FF0000"
  }
]

### Get all mood-entries
GET http://localhost:8080/entry
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### Get id of an entry
GET http://localhost:8080/entry/1
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### Update an entry
PUT http://localhost:8080/entry/1
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "mood": "MEH",
  "journal": "Could be better today",
  "color": "#FF0000"
}

### Delete an entry
DELETE http://localhost:8080/entry/1
Content-Type: application/json
Authorization: Bearer {{auth_token}}